export const en = {
  text1: 'My stats',
  text2: 'USDT balance',
  test3: 'CPS balance',
  text4: 'Liquidity PoolUSDT',
  text5: 'Flow cell CPS',
  text6: 'Flow Pool Proportion',
  text7: 'NFT statistics',
  text8: 'NFT price',
  text9: 'Total NFT',
  text10: 'NFT circulation',
  text11: 'NFT full mining computing power',
  text12: 'Holder',
  text13: 'CPS statistics',
  text14: 'CPS price',
  text15: 'Total CPS',
  text16: 'CPS circulation',
  text17: 'Liquidity pool value',
  text18: 'Partner',
  text19: 'Deep Cooperation',
  test20: 'If you encounter any problem, please email us in time',
  text21: 'Copy',
  text22: 'We respect your privacy.',
  text23: 'NFT mining pool',
  text24: 'Price',
  text25: 'snap up now',
  text26: 'NFT Mining Pool Data',
  text27: 'Total NFT',
  text28: 'NFT Circulation',
  text29: 'NFT Full Mining Computing Power',
  text30: 'Holder',
  text31: 'My NFT Computing Power',
  text32: 'NFT Computing Power',
  text33: 'NFT Weighted Computing Power',
  text34: 'CPS To Be Harvested',
  text35: 'Pledge NFT Now',
  text36: 'Receive',
  text37: 'Invite Friends To Earn',
  text38: 'CPS To Be Unlocked',
  text39: 'Available CPS',
  text40: 'Honor Value',
  text41: 'Liquidity Mining Gives Income',
  text42: 'CPS To Be Unlocked',
  text43: 'Available CPS',
  text44: 'NFT Node Mining Income',
  text45: 'CPS To Be Unlocked',
  text46: 'Available CPS',
  text47: 'Add Liquidity',
  text48: 'Add It Now',
  text49: 'Please Enter Amount',
  text50: 'Balance:',
  text51: 'Total Liquidity',
  text52: 'Number Of Flow Cells',
  text53: 'Add',
  text54: 'Already Pledged',
  text55: 'Approve',
  text56: 'Approving',
  text57: 'Take Out',
  text58: 'Invite Link',
  text59: 'My Invitation',
  text60: 'Recommended Data',
  text61: 'View referral and team size',
  text62: 'Exchange',
  text63: 'Exchange now'
}
