export const en = {
  text1: 'My stats',
  text2: 'USDT balance',
  test3: 'CPS balance',
  text4: 'Liquidity PoolUSDT',
  text5: 'Flow cell CPS',
  text6: 'Flow Pool Proportion',
  text7: 'NFT statistics',
  text8: 'NFT price',
  text9: 'Total NFT',
  text10: 'NFT circulation',
  text11: 'NFT full mining computing power',
  text12: 'Holder',
  text13: 'CPS statistics',
  text14: 'CPS price',
  text15: 'Total CPS',
  text16: 'CPS circulation',
  text17: 'Liquidity pool value',
  text18: 'Partner',
  text19: 'Deep Cooperation',
  test20: 'If you encounter any problem, please email us in time',
  text21: 'Copy',
  text22: 'We respect your privacy.',
  text23: 'NFT mining pool',
  text24: 'Price',
  text25: 'snap up now',
  text26: 'NFT Mining Pool Data',
  text27: 'Total NFT',
  text28: 'NFT Circulation',
  text29: 'NFT Full Mining Computing Power',
  text30: 'Holder',
  text31: 'My NFT Computing Power',
  text32: 'NFT Computing Power',
  text33: 'NFT Weighted Computing Power',
  text34: 'CPS To Be Harvested',
  text35: 'Pledge NFT Now',
  text36: 'Receive',
  text37: 'Invite Friends To Earn',
  text38: 'CPS To Be Unlocked',
  text39: 'Available CPS',
  text40: 'Honor Value',
  text41: 'Liquidity Mining Gives Income',
  text42: 'CPS To Be Unlocked',
  text43: 'Available CPS',
  text44: 'NFT Node Mining Income',
  text45: 'CPS To Be Unlocked',
  text46: 'Available CPS',
  text47: 'Add Liquidity',
  text48: 'Add It Now',
  text49: 'Please Enter Amount',
  text50: 'Balance:',
  text51: 'Total Liquidity',
  text52: 'Number Of Flow Cells',
  text53: 'Add',
  text54: 'Already Pledged',
  text55: 'Approve',
  text56: 'Approving',
  text57: 'Take Out',
  text58: 'Invite Link',
  text59: 'My Invitation',
  text60: 'Recommended Data',
  text61: 'View referral and team size',
  text62: 'Exchange',
  text63: 'Exchange now',
  text64: 'My wallet',
  text65: 'Exchange',
  text66: 'Fluidity',
  text67: 'Waiting',
  text100: 'Pledge',
  text101: 'Reward',
  text102: 'The Total Pledge',
  text103: 'Cps To Be Withdrawn Income',
  text104: 'Quantity To Be Pledged',
  text105: 'Period',
  text106: '90Days',
  text107: '150Days',
  text108: '210Days',
  text109: 'Demand Pledge',
  text110: 'Pledge Now',
  text111: 'Pledged Amount',
  text112: 'Unlock Time',
  text113: 'Output Amount',
  text114: 'Take Out',
  text115: 'LP Pledge dividens',
  text116: 'Receive Lp Pledge Dividends',
  text117:
    '0.5 Times The Computing Power For Current Deposits, Double The Computing Power For 90 Days, 1.5 Times The Computing Power For 150 Days, And Double The Computing Power For 210 Days',
  text118: 'Partner',
  text119: 'Deep Partner',
  text120: 'If you encounter any problem, please email us in time',
  text121: 'We respect your privacy',
  text122: 'Invite Friends To Earn',
  text123: 'Cps To Be Unlocked',
  text124: 'Available Cps',
  text125: 'Honor Value',
  text126: 'Liquidity Mining Gives Income',
  text127: 'NFT Node Mining Income',
  text128:
    'After mining and harvesting, 30% will go to the wallet, 20% will be released through preaching, and 50% will be released through 365 antennas, making the ecology more stable Thoughtful suggestion: Do not operate frequently, because you need to pay GAS for '
}
